// Package cataas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package cataas

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CatRandomTextParamsType.
const (
	Medium CatRandomTextParamsType = "medium"
	Small  CatRandomTextParamsType = "small"
	Square CatRandomTextParamsType = "square"
	Xsmall CatRandomTextParamsType = "xsmall"
)

// Valid indicates whether the value is a known member of the CatRandomTextParamsType enum.
func (e CatRandomTextParamsType) Valid() bool {
	switch e {
	case Medium:
		return true
	case Small:
		return true
	case Square:
		return true
	case Xsmall:
		return true
	default:
		return false
	}
}

// Defines values for CatRandomTextParamsFilter.
const (
	Custom CatRandomTextParamsFilter = "custom"
	Mono   CatRandomTextParamsFilter = "mono"
	Negate CatRandomTextParamsFilter = "negate"
)

// Valid indicates whether the value is a known member of the CatRandomTextParamsFilter enum.
func (e CatRandomTextParamsFilter) Valid() bool {
	switch e {
	case Custom:
		return true
	case Mono:
		return true
	case Negate:
		return true
	default:
		return false
	}
}

// Defines values for CatRandomTextParamsFit.
const (
	Contain CatRandomTextParamsFit = "contain"
	Cover   CatRandomTextParamsFit = "cover"
	Fill    CatRandomTextParamsFit = "fill"
	Inside  CatRandomTextParamsFit = "inside"
	Outside CatRandomTextParamsFit = "outside"
)

// Valid indicates whether the value is a known member of the CatRandomTextParamsFit enum.
func (e CatRandomTextParamsFit) Valid() bool {
	switch e {
	case Contain:
		return true
	case Cover:
		return true
	case Fill:
		return true
	case Inside:
		return true
	case Outside:
		return true
	default:
		return false
	}
}

// Defines values for CatRandomTextParamsPosition.
const (
	Bottom      CatRandomTextParamsPosition = "bottom"
	Center      CatRandomTextParamsPosition = "center"
	Left        CatRandomTextParamsPosition = "left"
	LeftBottom  CatRandomTextParamsPosition = "left bottom"
	LeftTop     CatRandomTextParamsPosition = "left top"
	Right       CatRandomTextParamsPosition = "right"
	RightBottom CatRandomTextParamsPosition = "right bottom"
	RightTop    CatRandomTextParamsPosition = "right top"
	Top         CatRandomTextParamsPosition = "top"
)

// Valid indicates whether the value is a known member of the CatRandomTextParamsPosition enum.
func (e CatRandomTextParamsPosition) Valid() bool {
	switch e {
	case Bottom:
		return true
	case Center:
		return true
	case Left:
		return true
	case LeftBottom:
		return true
	case LeftTop:
		return true
	case Right:
		return true
	case RightBottom:
		return true
	case RightTop:
		return true
	case Top:
		return true
	default:
		return false
	}
}

// Defines values for CatRandomTextParamsFont.
const (
	AndaleMono    CatRandomTextParamsFont = "Andale Mono"
	Arial         CatRandomTextParamsFont = "Arial"
	ArialBlack    CatRandomTextParamsFont = "Arial Black"
	ComicSansMS   CatRandomTextParamsFont = "Comic Sans MS"
	CourierNew    CatRandomTextParamsFont = "Courier New"
	Georgia       CatRandomTextParamsFont = "Georgia"
	Impact        CatRandomTextParamsFont = "Impact"
	TimesNewRoman CatRandomTextParamsFont = "Times New Roman"
	Verdana       CatRandomTextParamsFont = "Verdana"
	Webdings      CatRandomTextParamsFont = "Webdings"
)

// Valid indicates whether the value is a known member of the CatRandomTextParamsFont enum.
func (e CatRandomTextParamsFont) Valid() bool {
	switch e {
	case AndaleMono:
		return true
	case Arial:
		return true
	case ArialBlack:
		return true
	case ComicSansMS:
		return true
	case CourierNew:
		return true
	case Georgia:
		return true
	case Impact:
		return true
	case TimesNewRoman:
		return true
	case Verdana:
		return true
	case Webdings:
		return true
	default:
		return false
	}
}

// Cat defines model for Cat.
type Cat struct {
	CreatedAt string   `json:"createdAt"`
	Id        string   `json:"id"`
	Mimetype  string   `json:"mimetype"`
	Tags      []string `json:"tags"`
	Url       *string  `json:"url,omitempty"`
}

// CatRandomTextParams defines parameters for CatRandomText.
type CatRandomTextParams struct {
	Type     *CatRandomTextParamsType     `form:"type,omitempty" json:"type,omitempty"`
	Filter   *CatRandomTextParamsFilter   `form:"filter,omitempty" json:"filter,omitempty"`
	Fit      *CatRandomTextParamsFit      `form:"fit,omitempty" json:"fit,omitempty"`
	Position *CatRandomTextParamsPosition `form:"position,omitempty" json:"position,omitempty"`
	Width    *float32                     `form:"width,omitempty" json:"width,omitempty"`
	Height   *float32                     `form:"height,omitempty" json:"height,omitempty"`
	Blur     *float32                     `form:"blur,omitempty" json:"blur,omitempty"`

	// R With custom filter, define red value between 0 and 255
	R *float32 `form:"r,omitempty" json:"r,omitempty"`

	// G With custom filter, define green value between 0 and 255
	G *float32 `form:"g,omitempty" json:"g,omitempty"`

	// B With custom filter, define blue value between 0 and 255
	B *float32 `form:"b,omitempty" json:"b,omitempty"`

	// Brightness With custom filter, define brightness
	Brightness *float32 `form:"brightness,omitempty" json:"brightness,omitempty"`

	// Saturation With custom filter, define saturation
	Saturation *float32 `form:"saturation,omitempty" json:"saturation,omitempty"`

	// Hue With custom filter, define hue
	Hue *float32 `form:"hue,omitempty" json:"hue,omitempty"`

	// Lightness With custom filter, define lightness
	Lightness      *float32                 `form:"lightness,omitempty" json:"lightness,omitempty"`
	Html           *bool                    `form:"html,omitempty" json:"html,omitempty"`
	Json           *bool                    `form:"json,omitempty" json:"json,omitempty"`
	Font           *CatRandomTextParamsFont `form:"font,omitempty" json:"font,omitempty"`
	FontSize       *float32                 `form:"fontSize,omitempty" json:"fontSize,omitempty"`
	FontColor      *string                  `form:"fontColor,omitempty" json:"fontColor,omitempty"`
	FontBackground *string                  `form:"fontBackground,omitempty" json:"fontBackground,omitempty"`
}

// CatRandomTextParamsType defines parameters for CatRandomText.
type CatRandomTextParamsType string

// CatRandomTextParamsFilter defines parameters for CatRandomText.
type CatRandomTextParamsFilter string

// CatRandomTextParamsFit defines parameters for CatRandomText.
type CatRandomTextParamsFit string

// CatRandomTextParamsPosition defines parameters for CatRandomText.
type CatRandomTextParamsPosition string

// CatRandomTextParamsFont defines parameters for CatRandomText.
type CatRandomTextParamsFont string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CatRandomText request
	CatRandomText(ctx context.Context, text string, params *CatRandomTextParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CatRandomText(ctx context.Context, text string, params *CatRandomTextParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCatRandomTextRequest(c.Server, text, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCatRandomTextRequest generates requests for CatRandomText
func NewCatRandomTextRequest(server string, text string, params *CatRandomTextParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "text", text, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cat/says/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter", *params.Filter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Fit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "fit", *params.Fit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Position != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "position", *params.Position, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Width != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "width", *params.Width, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Height != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "height", *params.Height, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Blur != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "blur", *params.Blur, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.R != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "r", *params.R, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.G != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "g", *params.G, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.B != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "b", *params.B, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Brightness != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "brightness", *params.Brightness, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Saturation != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "saturation", *params.Saturation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Hue != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "hue", *params.Hue, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Lightness != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "lightness", *params.Lightness, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Html != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "html", *params.Html, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Json != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "json", *params.Json, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Font != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "font", *params.Font, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FontSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "fontSize", *params.FontSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FontColor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "fontColor", *params.FontColor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FontBackground != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "fontBackground", *params.FontBackground, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CatRandomTextWithResponse request
	CatRandomTextWithResponse(ctx context.Context, text string, params *CatRandomTextParams, reqEditors ...RequestEditorFn) (*CatRandomTextResponse, error)
}

type CatRandomTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Cat
}

// Status returns HTTPResponse.Status
func (r CatRandomTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CatRandomTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CatRandomTextWithResponse request returning *CatRandomTextResponse
func (c *ClientWithResponses) CatRandomTextWithResponse(ctx context.Context, text string, params *CatRandomTextParams, reqEditors ...RequestEditorFn) (*CatRandomTextResponse, error) {
	rsp, err := c.CatRandomText(ctx, text, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCatRandomTextResponse(rsp)
}

// ParseCatRandomTextResponse parses an HTTP response from a CatRandomTextWithResponse call
func ParseCatRandomTextResponse(rsp *http.Response) (*CatRandomTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CatRandomTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Cat
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (image/*) unsupported

	}

	return response, nil
}
