// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cataas

import (
	"context"
	"net/http"

	"github.com/YourSurpriseCom/oapi-codegen-client/_test/cataas"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// CatRandomText provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) CatRandomText(ctx context.Context, text string, params *cataas.CatRandomTextParams, reqEditors ...cataas.RequestEditorFn) (*http.Response, error) {
	var tmpRet mock.Arguments
	if len(reqEditors) > 0 {
		tmpRet = _mock.Called(ctx, text, params, reqEditors)
	} else {
		tmpRet = _mock.Called(ctx, text, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CatRandomText")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *cataas.CatRandomTextParams, ...cataas.RequestEditorFn) (*http.Response, error)); ok {
		return returnFunc(ctx, text, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *cataas.CatRandomTextParams, ...cataas.RequestEditorFn) *http.Response); ok {
		r0 = returnFunc(ctx, text, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *cataas.CatRandomTextParams, ...cataas.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, text, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientInterface_CatRandomText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatRandomText'
type MockClientInterface_CatRandomText_Call struct {
	*mock.Call
}

// CatRandomText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - params *cataas.CatRandomTextParams
//   - reqEditors ...cataas.RequestEditorFn
func (_e *MockClientInterface_Expecter) CatRandomText(ctx interface{}, text interface{}, params interface{}, reqEditors ...interface{}) *MockClientInterface_CatRandomText_Call {
	return &MockClientInterface_CatRandomText_Call{Call: _e.mock.On("CatRandomText",
		append([]interface{}{ctx, text, params}, reqEditors...)...)}
}

func (_c *MockClientInterface_CatRandomText_Call) Run(run func(ctx context.Context, text string, params *cataas.CatRandomTextParams, reqEditors ...cataas.RequestEditorFn)) *MockClientInterface_CatRandomText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *cataas.CatRandomTextParams
		if args[2] != nil {
			arg2 = args[2].(*cataas.CatRandomTextParams)
		}
		var arg3 []cataas.RequestEditorFn
		var variadicArgs []cataas.RequestEditorFn
		if len(args) > 3 {
			variadicArgs = args[3].([]cataas.RequestEditorFn)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClientInterface_CatRandomText_Call) Return(response *http.Response, err error) *MockClientInterface_CatRandomText_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockClientInterface_CatRandomText_Call) RunAndReturn(run func(ctx context.Context, text string, params *cataas.CatRandomTextParams, reqEditors ...cataas.RequestEditorFn) (*http.Response, error)) *MockClientInterface_CatRandomText_Call {
	_c.Call.Return(run)
	return _c
}
