// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cataas

import (
	"context"

	"github.com/YourSurpriseCom/oapi-codegen-client/_test/cataas"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientWithResponsesInterface creates a new instance of MockClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type MockClientWithResponsesInterface struct {
	mock.Mock
}

type MockClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterface_Expecter {
	return &MockClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// CatRandomTextWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) CatRandomTextWithResponse(ctx context.Context, text string, params *cataas.CatRandomTextParams, reqEditors ...cataas.RequestEditorFn) (*cataas.CatRandomTextResponse, error) {
	var tmpRet mock.Arguments
	if len(reqEditors) > 0 {
		tmpRet = _mock.Called(ctx, text, params, reqEditors)
	} else {
		tmpRet = _mock.Called(ctx, text, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CatRandomTextWithResponse")
	}

	var r0 *cataas.CatRandomTextResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *cataas.CatRandomTextParams, ...cataas.RequestEditorFn) (*cataas.CatRandomTextResponse, error)); ok {
		return returnFunc(ctx, text, params, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *cataas.CatRandomTextParams, ...cataas.RequestEditorFn) *cataas.CatRandomTextResponse); ok {
		r0 = returnFunc(ctx, text, params, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cataas.CatRandomTextResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *cataas.CatRandomTextParams, ...cataas.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, text, params, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_CatRandomTextWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatRandomTextWithResponse'
type MockClientWithResponsesInterface_CatRandomTextWithResponse_Call struct {
	*mock.Call
}

// CatRandomTextWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - params *cataas.CatRandomTextParams
//   - reqEditors ...cataas.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) CatRandomTextWithResponse(ctx interface{}, text interface{}, params interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_CatRandomTextWithResponse_Call {
	return &MockClientWithResponsesInterface_CatRandomTextWithResponse_Call{Call: _e.mock.On("CatRandomTextWithResponse",
		append([]interface{}{ctx, text, params}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_CatRandomTextWithResponse_Call) Run(run func(ctx context.Context, text string, params *cataas.CatRandomTextParams, reqEditors ...cataas.RequestEditorFn)) *MockClientWithResponsesInterface_CatRandomTextWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *cataas.CatRandomTextParams
		if args[2] != nil {
			arg2 = args[2].(*cataas.CatRandomTextParams)
		}
		var arg3 []cataas.RequestEditorFn
		var variadicArgs []cataas.RequestEditorFn
		if len(args) > 3 {
			variadicArgs = args[3].([]cataas.RequestEditorFn)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_CatRandomTextWithResponse_Call) Return(catRandomTextResponse *cataas.CatRandomTextResponse, err error) *MockClientWithResponsesInterface_CatRandomTextWithResponse_Call {
	_c.Call.Return(catRandomTextResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_CatRandomTextWithResponse_Call) RunAndReturn(run func(ctx context.Context, text string, params *cataas.CatRandomTextParams, reqEditors ...cataas.RequestEditorFn) (*cataas.CatRandomTextResponse, error)) *MockClientWithResponsesInterface_CatRandomTextWithResponse_Call {
	_c.Call.Return(run)
	return _c
}
